Julio review of module 3
cgps-group/digitalepiworkshopNigeria pull request #1
Opened 2024-02-25 18:04 UTC by juliofdiaz

@natacha-couto I have reviewed module 3. I am on the fence in terms of adding the pipeline graph showing the assembly step. Could you please add Nabil as a contributor and assign this to him?

2024-02-25 18:07 UTC, juliofdiaz commented
I've added Nabil, once he accepts. I'll comment him in for his support

2024-02-26 09:04 UTC, natacha-couto commented on module3/module3.qmd
> +In December 2020, three cases of primary bloodstream infections sustained by ertapenem-resistant *Klebsiella pneumoniae* were observed over a two-month period in the neonatal intensive care unit (NIC
change two-month period to two-week period. detection has an extra "f" at the end that needs to be removed.

2024-02-26 09:05 UTC, natacha-couto commented on module3/module3.qmd
> +The reference lab sent you the culture results from the faecal screening and the environmental sampling in an Excel file called ([`lab_results.xlsx`](data/lab_results.xlsx)). Faecal screening of the
not only faecal screening and environmental samples, the bloodstream strains as well.

2024-02-26 09:06 UTC, natacha-couto commented on module3/module3.qmd
> +One colony from each confirmed case and from each of Ithe two positive environmental samples were sent to the GHRU-Ibadan unit for sequencing.
an extra "I" on "the".

2024-02-26 09:07 UTC, natacha-couto commented on module3/module3.qmd
> +The /data directory will serve as the input directory for the GHRU assembly pipeline. You can practice fetching the data from a remote location such as Figshare, ENA or SRA folling the instructions i
error in "following"

2024-02-26 10:20 UTC, natacha-couto commented on module3/module3.qmd
> +You can use the same commad to copy the assemblies to your local machine (hint: `scp -r` helps you move an entire directory).
it should be command

2024-02-26 10:20 UTC, natacha-couto commented on module3/module3.qmd
> +You can use tools sucha as `wget` or `curl` to fetch data from a remote location such as Figshare, ENA or SRA. For example, you can fetch the data from the following Figshare link:
it should be such not "sucha"

2024-02-26 10:24 UTC, natacha-couto requested changes
changes are needed

2024-02-26 10:27 UTC, natacha-couto commented on module3/data/~$lab_results.xlsx
erase this file please

2024-02-26 10:27 UTC, natacha-couto requested changes
erase file

2024-02-26 11:14 UTC, closed without merging